#!/bin/bash -l
#PBS -l select=7:system=polaris
#PBS -l place=scatter
#PBS -l walltime=00:59:00
#PBS -l filesystems=home:eagle
#PBS -q debug-scaling
#PBS -A DFTCalculations
module use /soft/modulefiles
module load spack-pe-base cmake
module load PrgEnv-gnu/8.6.0
module load gcc-native/13.2
module load cuda/12.9
module load craype-accel-nvidia80
xport NCCL_NET_GDR_LEVEL=PHB
export NCCL_CROSS_NIC=1
#export NCCL_COLLNET_ENABLE=0
export NCCL_NET="AWS Libfabric"
#export NCCL_DEBUG=INFO
export LD_LIBRARY_PATH=/soft/libraries/aws-ofi-nccl/v1.9.1-aws-libfabric-1.22.0/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/soft/libraries/hwloc/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/phanim/softwares/DFTFEinstallationCuda12.9/dependencies/lib64
export LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBRARY_PATH
# Enable GPU-MPI (if supported by application)
export MPICH_GPU_SUPPORT_ENABLED=0

# Change to working directory
cd ${PBS_O_WORKDIR}
ls

# MPI/OpenMP configuration
NNODES=$(wc -l < $PBS_NODEFILE)

NRANKS_PER_NODE=32
NTHREADS=1
NDEPTH=1

export OMP_NUM_THREADS=${NTHREADS}
export DFTFE_NUM_THREADS=${NTHREADS}

NTOTRANKS=$((NNODES * NRANKS_PER_NODE))

echo "NUM_OF_NODES       = ${NNODES}"
echo "TOTAL_NUM_RANKS    = ${NTOTRANKS}"
echo "RANKS_PER_NODE     = ${NRANKS_PER_NODE}"
echo "THREADS_PER_RANK   = ${NTHREADS}"

exe=/home/phanim/softwares/DFTFEinstallationCuda12.9/dftfe_PAWjctc/installGPUAwareOFF/real/dftfe

mpiexec \
    -n ${NTOTRANKS} \
    --ppn ${NRANKS_PER_NODE} \
    --depth=${NDEPTH} \
    --cpu-bind depth \
    --env OMP_NUM_THREADS=${NTHREADS} \
    ${exe} FinalCPU.prm \
    > Final_out_CPU_7Node_192MPI_840WFC.op 2>&1