#!/bin/bash
#SBATCH --job-name=pawGPU # Job name
#SBATCH --ntasks-per-node=12 # Number of tasks per node
#SBATCH --nodes=1
#SBATCH --time=01:50:00 # Time limit hrs:min:sec


​
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"
#echo "CPU bind Info  = $SLURM_CPU_BIND"    
echo "CPU on node  = $SLURM_CPUS_ON_NODE"         
​
module load spack
module load openmpi/5.0.6-gcc-13.3.0-ytficip nccl/2.23.4-1-gcc-13.3.0-xyspmp2 gdrcopy/2.4.1-gcc-13.3.0-dvwa323
export LIBRARY_PATH="/storage/dftfeDependenciesNoMKL/linAlgLibs/install/lib:$LIBRARY_PATH"
export OMP_NUM_THREADS=1
export DFTFE_NUM_THREADS=1
export DEAL_II_NUM_THREADS=1


mpirun -n $SLURM_NTASKS  /home/kartickr/dftfe_development/DFTFE_PAWReimplementation/build_mergePAWwithPGD/release/real/dftfe Mesh.prm > Out_Mesh.op


















