#!/bin/sh
#SBATCH -A nti115
#SBATCH -J fullPAW
#SBATCH -t 01:15:00
#SBATCH -p batch
#SBATCH -N 2
#SBATCH --gpus-per-node 8
#SBATCH --ntasks-per-gpu 1
#SBATCH --gpu-bind closest
##SBATCH --dependency=singleton
export OMP_NUM_THREADS=1
export MPICH_VERSION_DISPLAY=1
export MPICH_ENV_DISPLAY=1
export MPICH_OFI_NIC_POLICY=NUMA
export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_SMP_SINGLE_COPY_MODE=NONE

export FI_MR_CACHE_MONITOR=disabled

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INST/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INST/lib/lib64
export LD_LIBRARY_PATH=$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export DFTFE_NUM_THREADS=3
export ELPA_DEFAULT_omp_threads=3
module list
export BASE=/lustre/orion/nti115/scratch/kartickr/DFTFE/dftfe_PAWjctc/build/release/real



srun -n $SLURM_NTASKS -c 7 --gpu-bind closest $BASE/dftfe 1.prm > out_1.op
srun -n $SLURM_NTASKS -c 7 --gpu-bind closest $BASE/dftfe 2.prm > out_2.op
srun -n $SLURM_NTASKS -c 7 --gpu-bind closest $BASE/dftfe 3.prm > out_3.op
#srun -n $SLURM_NTASKS -c 7 --gpu-bind closest $BASE/dftfe 7.prm > out_7.op
