#!/bin/sh
#SBATCH -A nti115
#SBATCH -J fullPAW
#SBATCH -t 00:59:00
#SBATCH -p batch
#SBATCH -N 20
#SBATCH --gpus-per-node 8
#SBATCH --ntasks-per-gpu 1
#SBATCH --gpu-bind closest
##SBATCH --dependency=singleton
export OMP_NUM_THREADS=1
export MPICH_VERSION_DISPLAY=1
export MPICH_ENV_DISPLAY=1
export MPICH_OFI_NIC_POLICY=NUMA
export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_SMP_SINGLE_COPY_MODE=NONE

export FI_MR_CACHE_MONITOR=disabled
export HIP_LAUNCH_BLOCKING=1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INST/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INST/lib/lib64
export LD_LIBRARY_PATH=$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export DFTFE_NUM_THREADS=1
export ELPA_DEFAULT_omp_threads=3
module list
export BASE=/lustre/orion/nti115/scratch/kartickr/DFTFE/dftfe_PAWjctc/build/release/complex


srun -n $SLURM_NTASKS -c 7 --gpu-bind closest $BASE/dftfe 1.prm > Deltaout_1.op
